steps:
  - uses: actions/checkout@v3
  - name: Setup emsdk
    run: |
      git clone https://github.com/emscripten-core/emsdk.git
      cd emsdk
      ./emsdk install latest
      ./emsdk activate latest
      source ./emsdk_env.sh
  - name: Build WASM
    run: make js
